spring:
  application:
    name: midia-extrator-sv

  rabbitmq: # Movidas especificamente para dentro do spring, entender porque !
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_NODE_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASSWORD}

server:
  port: ${MIDIA_EXTRATOR_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${APP_MIDIA_EXTRATOR_HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

