spring:
  application:
    name: gateway-sv
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orquestrador-route
          uri: http://localhost:8083  # Manda pro orquestrador local
          predicates:
            - Path=/orquestrador/**
        - id: orquestrador-eureka-route
            # lb:// = Pede para o LoadBalancer achar o serviço pelo nome no Eureka
          uri: lb://ORQUESTRADOR-SV
          predicates:
              # A URL no Gateway OBRIGATORIAMENTE precisa começar com o nome do serviço
              - Path=/orquestrador-sv/**
          filters:
              # Remove o "/orquestrador-sv" da URL antes de repassar para o microserviço
              - StripPrefix=1

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE # Para vermos a rota bater