spring:
  application:
    name: gateway-sv
  cloud:
    gateway:
      routes:
        - id: orquestrador-rota
          uri: lb://ORQUESTRADOR-SV
          predicates:
            - Path=/orquestrador-sv/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${APP_HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always