spring:
  profiles:
    active: dev
  application:
    name: gateway-sv
  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: orquestrador-route
            uri: http://orquestrador:8083
            predicates:
              - Path=/orquestrador/**

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: gateway

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.mvc: DEBUG
