version: '3.8'

services:
  eureka-server:
    build:
      # Esse trecho é combinado com o COPY do dockerfile = ..eureka-erver/target/*.jar
      context: ../eureka-server
      dockerfile: ../docker/java-Dockerfile
    container_name: easy-video-eureka
    ports:
      - "8761:8761"
    env_file:
      - ../variaveis/compose/.env.eureka.compose
    networks:
      - easy-video
    restart: unless-stopped

  gateway:
    build:
      context: ../gateway
      dockerfile: ../docker/java-Dockerfile
    container_name: easy-video-gateway
    ports:
      - "8082:8082"
    env_file:
      - ../variaveis/compose/.env.gateway.compose
    networks:
      - easy-video
    restart: unless-stopped
    depends_on:
      eureka-server: 
        condition: service_healthy 

  orquestrador:
    build:
      context: ../orquestrador
      dockerfile: ../docker/java-Dockerfile
    container_name: easy-video-orquestrador
    ports:
      - "8083:8083"
    env_file:
      - ../variaveis/compose/.env.orquestrador.compose
    networks:
      - easy-video
    restart: unless-stopped
    depends_on:
      eureka-server: 
        condition: service_healthy 
      rabbitmq: 
        condition: service_healthy

  midia-extrator:
    build:
      context: ../midia-extrator
      dockerfile: ../docker/java-Dockerfile
    container_name: easy-video-midia-extrator
    ports:
      - "8084:8084"
    env_file:
      - ../variaveis/compose/.env.midia-extrator.compose
    networks:
      - easy-video
    restart: unless-stopped
    depends_on:
      eureka-server: 
        condition: service_healthy 
      rabbitmq: 
        condition: service_healthy

  rabbitmq:
    build:
      context: .
      dockerfile: ../docker/rabbitmq-Dockerfile
    container_name: easy-video-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ../variaveis/compose/.env.rabbitmq.compose
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq     # Mapeando diretório do host para volume no container
    networks:
      - easy-video
    restart: unless-stopped


  grafana:
    build:
      context: .
      dockerfile: ../docker/grafana-Dockerfile
    container_name: easy-video-grafana
    ports:
      - "3000:3000"
    env_file:
      - ../variaveis/compose/.env.grafana.compose 
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_log:/var/log/grafana
    networks:
      - easy-video
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: easy-video-prometheus
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s       
      timeout: 10s        
      retries: 3          
      start_period: 40s
    volumes:
      - ../observabilidade/prometheus.yml:/etc/prometheus/prometheus.yml # bindMount - Mapeia arquivo no host para arquivo dentro do container
      - prometheus_data:/prometheus
    networks:
      - easy-video
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: easy-video-loki
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/actuator/health"]
      interval: 30s       
      timeout: 10s        
      retries: 3          
      start_period: 40s
    volumes:
      - ../observabilidade/loki/loki-config.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml       # Sobrescreve o comando padrão do container para usar o arquivo de configuração personalizado
    networks:
      - easy-video
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: easy-video-promtail
    volumes:
      # Acesso a logs docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

      - ../observabilidade/loki/promtail-config.yml:/etc/promtail/config.yml 
      - promtail_data:/tmp
    command: -config.file=/etc/promtail/config.yml
    networks:
      - easy-video
    restart: unless-stopped

volumes:
  rabbitmq_data:    # Declarando o volume para persistência
    driver: local   # Driver padrão do Docker para volumes
  grafana_data:
    driver: local
  grafana_log:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    driver: local
  promtail_data:
    driver: local
  
networks:
  easy-video:
    driver: bridge
 


