spring:
  application:
    name: orquestrador-sv

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_NODE_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASSWORD}

server:
  port: ${ORQUESTRADOR_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${APP_ORQUESTRADOR_HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always