spring:
  application:
    name: download-sv

  rabbitmq: # Movidas especificamente para dentro do spring, entender porque !
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${APP_HOSTNAME}

logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    br.com.midiaconverte: DEBUG