spring:
  application:
    name: download-sv

  rabbitmq: # Movidas especificamente para dentro do spring, entender porque !
    host: rabbitmq
    port: 5672
    username: athos
    password: 123

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: download

logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    br.com.midiaconverte: DEBUG