spring:
  application:
    name: eureka-sv

server:
  port: ${PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_HOSTNAME}
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always